<?php
$subject = (string)($_GET['gäller'] ?? $route['formSubject'] ?? 'Förfrågan från webbplatsen');
$formError = (string)($_SESSION['form_error'] ?? '');
unset($_SESSION['form_error']);
?>
<main id="main">
  <section class="page-hero page-hero--simple"><div class="container"><nav class="breadcrumbs"><a href="/">Start</a><span>/</span><span>Kontakt</span></nav><p class="eyebrow eyebrow--light">Kontakta LOTS</p><h1><?= e((string)$route['title']) ?></h1><p class="page-hero__lead">Beskriv verksamheten och vad ni behöver hjälp med. Ni behöver inte veta vilken produkt som passar.</p></div></section>
  <section class="content-section"><div class="container contact-layout"><form class="contact-form" action="/api/contact.php" method="post" data-contact-form><?php if ($formError !== ''): ?><p class="form-error" role="alert"><?= e($formError) ?></p><?php endif; ?><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="subject" value="<?= e($subject) ?>"><div class="honeypot" aria-hidden="true"><label>Webbplats<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="form-grid"><label><span>Namn *</span><input name="name" autocomplete="name" required maxlength="120"></label><label><span>Organisation</span><input name="organisation" autocomplete="organization" maxlength="160"></label><label><span>E-post *</span><input type="email" name="email" autocomplete="email" required maxlength="180"></label><label><span>Telefon</span><input type="tel" name="phone" autocomplete="tel" maxlength="50"></label></div><label><span>Vad kan vi hjälpa er med? *</span><textarea name="message" required minlength="10" maxlength="5000" rows="7"></textarea></label><label class="consent"><input type="checkbox" name="consent" value="1" required><span>Jag godkänner att LOTS behandlar uppgifterna för att besvara min förfrågan. *</span></label><button class="button button--primary" type="submit">Skicka förfrågan</button><p class="form-note">Fält markerade med * är obligatoriska.</p></form><aside class="contact-details"><h2>Direktkontakt</h2><a href="tel:+4687112211"><span>Telefon</span><strong>08-711 22 11</strong></a><a href="mailto:info@lotsab.se"><span>E-post</span><strong>info@lotsab.se</strong></a><div><span>Besöksadress</span><strong>Jägerhorns väg 8<br>141 75 Kungens kurva</strong></div><p>Vanligtvis återkommer vi inom en arbetsdag.</p></aside></div></section>
</main>
